@echo off
REM ===========================================================================
REM  ShortForge - start automatically when you log in.
REM  Just double-click this file. No admin rights, no paths to type.
REM
REM  Uses the Windows Startup folder rather than Task Scheduler: schtasks needs
REM  privileges that many machines refuse ("Access is denied"), while anything
REM  in the Startup folder is launched by Explorer as you, every logon.
REM ===========================================================================
setlocal enabledelayedexpansion
title ShortForge autostart
cd /d "%~dp0"

set "STARTUP=%APPDATA%\Microsoft\Windows\Start Menu\Programs\Startup"
set "TG=%STARTUP%\ShortForge Telegram.bat"
set "QU=%STARTUP%\ShortForge Queue.bat"

echo ============================================================
echo   ShortForge - start automatically at logon
echo   Program folder: "%CD%"
echo   Startup folder: "%STARTUP%"
echo ============================================================
echo.
if exist "%TG%" echo   [currently ON]  Telegram mode
if exist "%QU%" echo   [currently ON]  Queue mode
if not exist "%TG%" if not exist "%QU%" echo   [currently OFF] nothing starts automatically
echo.
echo   1  Everything      - dashboard UI + Telegram listener + queue worker
echo   2  Queue only      - work through queued links, no UI, no Telegram
echo   3  Turn autostart OFF
echo   4  Cancel
echo.
set "CHOICE="
set /p CHOICE=Type 1, 2, 3 or 4 then press Enter:

if "%CHOICE%"=="1" goto :telegram
if "%CHOICE%"=="2" goto :queue
if "%CHOICE%"=="3" goto :remove
goto :cancel

:telegram
set "TARGET=%~dp0start_all.bat"
set "LINK=%TG%"
set "OTHER=%QU%"
set "NAME=Everything (UI + Telegram + queue)"
goto :install

:queue
set "TARGET=%~dp0run_queue.bat"
set "LINK=%QU%"
set "OTHER=%TG%"
set "NAME=Queue mode"
goto :install

:install
if not exist "%TARGET%" (
  echo.
  echo [FAIL] Could not find "%TARGET%"
  echo        Run this file from inside your ShortForge folder.
  goto :done
)
if not exist "%STARTUP%" (
  echo.
  echo [FAIL] Startup folder not found:
  echo        "%STARTUP%"
  goto :done
)
REM Only one mode at a time - Telegram mode already drains the queue.
if exist "%OTHER%" del "%OTHER%" >nul 2>&1

REM Write a tiny launcher into Startup that calls the real script in place.
REM %CD% has no trailing backslash, so the generated `cd` can't break on quoting.
> "%LINK%" echo @echo off
>>"%LINK%" echo REM Auto-generated by install_autostart.bat - delete this file to turn it off.
>>"%LINK%" echo cd /d "%CD%"
>>"%LINK%" echo call "%TARGET%"

if not exist "%LINK%" (
  echo.
  echo [FAIL] Could not write to the Startup folder. Antivirus may be blocking it.
  echo        Manual alternative: press Win+R, type  shell:startup  and press Enter,
  echo        then drag a shortcut to "%TARGET%" into the folder that opens.
  goto :done
)

echo.
echo [ok] %NAME% will now start automatically when you log in.
echo      Created: "%LINK%"
echo.
echo  Turn it off later: run this file again and choose 3.
echo.
REM Start it NOW as well, so autostart is proven today rather than at next boot -
REM the operator previously rebooted and found nothing had started.
set "STARTNOW="
set /p STARTNOW=Start it now too, to check it works? (Y/N):
if /i "%STARTNOW%"=="Y" (
  echo   Launching "%TARGET%" in a new window...
  start "ShortForge" cmd /c "%TARGET%"
  echo.
  echo   A new window opened. If notifications are set up you should get a
  echo   "ShortForge is awake" message on your phone within a few seconds.
  echo   You should also get a "ShortForge stopped" message when you close it -
  echo   that is how you can always tell whether it is really running.
)
goto :done

:remove
set "GONE=0"
if exist "%TG%" (del "%TG%" >nul 2>&1 & set "GONE=1")
if exist "%QU%" (del "%QU%" >nul 2>&1 & set "GONE=1")
REM Clean up any scheduled tasks from the older instructions, if they exist.
schtasks /delete /tn "ShortForgeTelegram" /f >nul 2>&1
schtasks /delete /tn "ShortForgeQueue" /f >nul 2>&1
echo.
if "!GONE!"=="1" (
  echo [ok] Autostart turned off. ShortForge will no longer start by itself.
) else (
  echo [ok] Autostart was not enabled - nothing to remove.
)
goto :done

:cancel
echo Cancelled - nothing changed.

:done
echo.
pause
endlocal
